dist: xenial
sudo: required
language: cpp
compiler: gcc

addons:
  apt:
    packages:
      - libsdl2-dev
      - libsdl2-mixer-dev

script:
  - sdl2-config --version
  - ./genie_gmake.sh
  - cd build
  - make

notifications:
  email: false
  