language: cpp
sudo: required
dist: trusty

os:
  - linux

compiler:
  - gcc

before_install:
  - if [ $TRAVIS_OS_NAME == linux ]; then 
      sudo apt-get update -qq;
      sudo apt-get install -y --no-install-recommends libsdl2-dev libsdl2-mixer-dev;
      ./genie_gmake.sh;
      cd build;
    fi

script: 
  - make
