dist: xenial
sudo: required
language: cpp
compiler: gcc

branches:
 only:
   - master

addons:
  apt:
    update: true
    packages:
      - libsdl2-dev
      - libsdl2-mixer-dev

before_install:
  
  # Download, make and install SDL2-2.0.8 (stable)
#  - |
#    travis_retry curl -L https://www.libsdl.org/release/SDL2-2.0.8.tar.gz | tar xz
#    cd SDL2-2.0.8
#    ./configure
#    make
#    sudo make install
#    cd ..
    
script:
  - sdl2-config --version
  - ./genie_gmake.sh
  - cd build
  - make

notifications:
  email: false
  