language: cpp
compiler: gcc
sudo: required
dist: trusty

before_install:
  # C++11
  sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  sudo apt-get update -qq;

install: 
  # C++11
  - sudo apt-get install -qq g++-5
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-5 90
  - sudo apt-get install -y --no-install-recommends libsdl2-dev libsdl2-mixer-dev;
  - ./genie_gmake.sh;
  
script:
  - cd build;
  - make
